name: Backend CI

on:
  push:
    branches: ["developer", "main"]
    paths:
      - '**.py' # Only changes happened in .py files
  pull_request:
    branches: ["developer", "main"]
    paths:
      - '**.py'

jobs:
  fronted-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Install Linting Tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint Python with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics